### ISSUE TITLE
Preview created GIFs

### ISSUE THREAD

**Issue by unfa** [polypmer/fissure-android#10]
It's be cool if the user could vie his creations right from Fissure, without searching the folder structure of his device. Also sharing the new GIFs from Fissure would be a great time-saver.

**Comment by fenimore** [comment]
So this ought to be the case, if you click the magnifying glass, it should take you to the gifs folder, with all the gifs in there. See what I mean?

**Comment by fenimore** [comment]
Also, I'll stick the sharing into another issue

**Comment by fenimore** [comment]
Oh, this was fixed A while ago
