### ISSUE TITLE
Copycat on Google Play

### ISSUE THREAD

**Issue by Poussinou** [polypmer/fissure-android#22]
Hi @fenimore 

I found this app on the Google Play Store: https://play.google.com/store/apps/details?id=easygifmaker.free

This guy just took your source code, added some ads in it and put it on the Store, without warning this is free software...

As you are the owner of the source code, feel free to open a request to google [here](https://support.google.com/legal/contact/lr_dmca?product=googleplay) to remove this copy from the Store, if it's your wish ;)

Don't forget to tell Google that:

* The app is licensed under GNU GPL v3 license and this guy is violating it;
* He is falsely claiming he made the app;
* Provide some screenshots of your own app.

**Comment by fenimore** [comment]
wow thank you!

**Comment by fenimore** [comment]
and this dev has got like way more downloads than me wtf!?!? :D

**Comment by NitroNils** [comment]
So impove this one, please!

**Comment by Poussinou** [comment]
This copycat is down, I'm closing this Issue.

If you find other copycats in the future, please report them here.
