### ISSUE TITLE
Image list clears when changing options

### ISSUE THREAD

**Issue by unfa** [polypmer/fissure-android#4]
Going to the setting screen causes all selected images to disappear. Kind of frustrating.

**Comment by fenimore** [comment]
I'm not sure how to fix this :S, but I agree, it's annoying.

**Comment by Swati4star** [comment]
Is it fixed?
I dont see this issue now.

**Comment by fenimore** [comment]
So it doesn't clear if you click the Android back button, but if you click the top right hand Home button it does clear

**Comment by fenimore** [comment]
Excellent fix, I see what you did, thanks I'm learning a lot from you :)
