### ISSUE TITLE
allow adding multiple images at once

### ISSUE THREAD

**Issue by unfa** [polypmer/fissure-android#8]
The file selection dialog used to add filrs allows only one file to be selected. Making this a multi-select would greatly speed up adding the images, especially for longer animations.

**Comment by fenimore** [comment]
Yeah, this is crucial, there's a stackoverflow question right up this alley too,
http://stackoverflow.com/questions/19513556/select-multiple-files-with-intent-action-get-content

**Comment by fenimore** [comment]
Works great! @Swati4star
